### DISCUSSION TITLE
postgrest in K8

### DISCUSSION THREAD

**Discussion by pralow** [PostgREST/postgrest#2191] [Q&A] [answered]
* PostgreSQL version: (if using docker, specify the image)

PostgreSQL 13.3 (Ubuntu 13.3-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
    
* PostgREST version: (if using docker, specify the image)

postgrest/postgrest    Latest version 

Trying to deploy the postgrest  in the Kubernetes (v1.19.7), Following is the deployment file 

     containers:
      - name: postgrest
        image: postgrest/postgrest
        ports:
        - containerPort: 3000
        env:
          - name: PGRST_DB_URI
            value: "sslmode=require sslrootcert=/Users/work/postgres/postgrest/ca.crt sslcert=/Users/work/postgres/postgrest/tls.crt sslkey=/Users/work/postgres/postgrest/tls.key host=dburl port=port dbname=dbname user=username password=password"
          - name: PGRST_DB_SCHEMA
            value: "public"
          - name: PGRST_DB_ANON_ROLE
            value: "rolename"

it is always saying not able error as "connection requires a valid client certificate", i tried passed the connection string in various format. All it is resulted in the same error. Any docs on how to deploy postgrest in kuberntes and connect to postgres via SSL. 

The connection to the same DB is working in MAC via SSL. ( only in kubernetes facing this SSL issue)

**Comment by wolfgangwalther** [comment]
> `value: "sslmode=require sslrootcert=/Users/work/postgres/postgrest/ca.crt sslcert=/Users/work/postgres/postgrest/tls.crt sslkey=/Users/work/postgres/postgrest/tls.key host=dburl port=port dbname=dbname user=username password=password"`

~This is not a valid libpq connection string.~ I gave an example in https://github.com/PostgREST/postgrest/issues/2098#issuecomment-1000557426 - did that not work?

**Comment by wolfgangwalther** [comment]
Also note, I just found out that you can use `PGRST_DB_URI="postgresql://"` - and then set everything else via PG environment variables (see https://github.com/PostgREST/postgrest/issues/1991#issuecomment-1003910285). Maybe that will work better for you?

**Comment by pralow** [comment]
InitContainer approach worked perfectly fine, where the cert are copied upfront. 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
spec:
  selector:
    matchLabels:
      app: postgrest
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      serviceAccountName: pgrest
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      initContainers:
      - name: postgpconfig 
        image: xxxx/dev/daas/pginit:0.1
        args:
          - /bin/sh
          - -c
          - cp -r /home/testuser/config/* /config/
        volumeMounts:
          - mountPath: /config
            name: server-config 
      containers:
      - name: postgrest
        image: postgrest/postgrest
        ports:
        - containerPort: 3000
        env:
          - name: PGRST_DB_URI
            value: "postgres://"
          - name: PGRST_DB_SCHEMA
            value: "public"
          - name: PGRST_DB_ANON_ROLE
            value: "pgpocappengine"
          - name: PGSSLROOTCERT
            value: "/config/ca.crt"
          - name: PGSSLKEY
            value: "/config/tls.key"
          - name: PGSSLCERT
            value:  "/config/tls.crt"
          - name: PGUSER
            value: ""
          - name: PGPASSWORD
            value: ""
          - name: PGHOST
            value: ""
          - name: PGPORT
            value: ""
          - name: PGDATABASE
            value: ""
        volumeMounts:
          - mountPath: /config
            name: server-config
      volumes:
      - name: server-config
        emptyDir: {}
```

if i try to mount the cert via secret. it is running into below issue 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
spec:
  selector:
    matchLabels:
      app: postgrest
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      serviceAccountName: pgrest
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: postgrest
        image: postgrest/postgrest
        ports:
        - containerPort: 3000
        env:
          - name: PGRST_DB_URI
            value: "postgres://"
          - name: PGRST_DB_SCHEMA
            value: "public"
          - name: PGRST_DB_ANON_ROLE
            value: "pgpocappengine"
          - name: PGSSLROOTCERT
            value: "/config/ca.crt"
          - name: PGSSLKEY
            value: "/config/tls.key"
          - name: PGSSLCERT
            value:  "/config/tls.crt"
          - name: PGUSER
            value: ""
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pgsecret
                key: password
          - name: PGHOST
            value: ""
          - name: PGPORT
            value: ""
          - name: PGDATABASE
            value: ""
        volumeMounts:
          - mountPath: /config
            name: server-config
      volumes:
      - name: server-config
        secret:
          secretName: pgcert
          defaultMode: 384 
```

failed: private key file \"/config/tls.key\" has group or world access; permissions should be u=rw (0600) or less\n connection to server at 

i tried all the permission combination in the defaultMode.

**Reply by wolfgangwalther** [reply]
Were you able to make it work?

**Comment by wolfgangwalther** [comment, marked as answer]
This seems to be much more of a kubernetes question by now that a question about PostgREST. I'm afraid we might not have the expertise here to actually help you how to set the right permissions. The error message is pretty clear - `0600` max. The fact that you're getting that message suggests that you are able to pass the file paths correctly to PostgREST.

**Reply by pralow** [reply]
Thank you for checking . It worked with Initcointainer with busybox image.  

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  namespace: pg-{{.Values.appName}}
spec:
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      serviceAccountName: pgrest
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      initContainers:
        - name: postgpconfig
          image: busybox:1.30
          command:
            - sh
            - -c
            - |-
              cp  /config/tls.key /temp/tls.key
              chmod 0600 /temp/tls.key
          volumeMounts:
            - mountPath: /config/tls.key
              subPath: tls.key
              name: server-config
            - mountPath: /config/tls.crt
              subPath: tls.crt
              name: server-config
            - mountPath: /config/ca.crt
              subPath: ca.crt
              name: server-config
            - mountPath: /temp
              name: temp
      containers:
        - name: postgrest
          image: postgrest/postgrest
          ports:
            - containerPort: 3000
          env:
            - name: PGRST_DB_URI
              value: "postgres://"
            - name: PGRST_DB_SCHEMA
              value: "public"
            - name: PGRST_DB_ANON_ROLE
              value: {{.Values.appName}}
            - name: PGSSLROOTCERT
              value: "/config/ca.crt"
            - name: PGSSLKEY
              value: "/temp/tls.key"
            - name: PGSSLCERT
              value:  "/config/tls.crt"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: <<secret Name>>
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: << secret Name>.
                  key: password
            - name: PGHOST
              value: "{{.Values.appName}}"
            - name: PGPORT
              value: "{{.Values.virtualPort}}"
            - name: PGDATABASE
              value: {{.Values.appName}}
          volumeMounts:
            - mountPath: /config/tls.key
              subPath: tls.key
              name: server-config
            - mountPath: /config/tls.crt
              subPath: tls.crt
              name: server-config
            - mountPath: /config/ca.crt
              subPath: ca.crt
              name: server-config
            - mountPath: /temp
              name: temp
      volumes:
        - name: temp
          emptyDir: {}
        - name: server-config
          secret:
            secretName: "pg-{{.Values.appName}}-tls"
            defaultMode: 384
            items:
              - key: tls.key
                path: tls.key
              - key: tls.crt
                path: tls.crt
              - key: ca.crt
                path: ca.crt
```
