### DISCUSSION TITLE
posgrest not connecting to DB if we use docker-compose.yml

### DISCUSSION THREAD

**Discussion by System-Integrator** [PostgREST/postgrest#2252] [Q&A] [answered]
### Environment

* PostgreSQL version: (if using docker, specify the image)
   postgres:13.4-alpine
* PostgREST version: (if using docker, specify the image)
   9
* Operating system: Ubuntu server

### Description of issue

(Expected behavior vs actual behavior)
Postgrest will connect to postgres DB.

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)
16/Apr/2022:19:26:59 +0000: Attempting to reconnect to the database in 16 seconds...
16/Apr/2022:19:27:36 +0000: {"details":"could not translate host name \"db\" to address: Try again\n","code":"","message":"Database connection error. Retrying the connection."}

**Comment by System-Integrator** [comment]
Error details:
{"details":"could not translate host name \"db\" to address: Try again\n","code":"","message":"Database connection error. Retrying the connection."}

db is Service Name of postgres Database in docker-compose file

**Comment by steve-chavez** [comment, marked as answer]
Can you share the `docker-compose` file?

**Comment by laurenceisla** [comment]
As Steve mentioned, the `docker-compose` file would help. In #2248 you mentioned that you used the file from the docs, I tested it without modifying anything and worked OK in my system (I'm using EndeavourOS). There's still a connection error at the start (maybe the PostgreSQL service isn't ready yet) but it connects eventually.

An [answer I found](https://stackoverflow.com/a/61141424) to a similar error is to add both to a network, maybe it helps. Something like:

```yml
# docker-compose.yml

version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user #In production this role should not be the same as the one used for the connection
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db
    links:
      - db:db
    networks:
      - pgnetwork
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    networks:
      - pgnetwork
  # Uncomment this if you want to persist the data.
  # volumes:
  #   - "./pgdata:/var/lib/postgresql/data"

networks:
  pgnetwork:
      driver: bridge

```
