### DISCUSSION TITLE
How does one get a protected spec in Swagger UI?

### DISCUSSION THREAD

**Discussion by dnk8n** [PostgREST/postgrest#2716] [Q&A] [answered]
### Environment

Below is how my docker-compose is configured:
``` yaml
postgrest:
    depends_on:
      postgres:
        condition: service_started
    environment:
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_PRE_REQUEST: auth.check_token
      PGRST_DB_SCHEMA: public
      PGRST_DB_URI: postgres://authenticator:authenticator@postgres:5432/example
      PGRST_JWT_SECRET: ***
      PGRST_OPENAPI_SECURITY_ACTIVE: "true"
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000
    image: postgrest/postgrest:v10.1.2
    networks:
      example_net: {}
    ports:
    - target: 3000
      published: "3000"
    restart: unless-stopped
  swagger:
    depends_on:
      postgrest:
        condition: service_started
    environment:
      URLS: '[ { url: "http://localhost:3000", name: "EXAMPLE" } ]'
    image: swaggerapi/swagger-ui:v4.18.1
    networks:
      example_net: {}
    ports:
    - target: 8080
      published: "8080"
```
![Screenshot from 2023-03-25 13-40-07](https://user-images.githubusercontent.com/3307753/227715351-927726cb-77f3-4edb-ae0c-349f10ef0194.png)

### Description of issue

I have the authorization button configured, and it works how I want it to for the only available public endpoint (the spec itself). When executed with the authorization header set, it returns json with the full protected spec.

But I don't see a way to get that spec loaded so that the protected endpoints are displayed. What is the standard way of achieving this?

I guess this not necessarily a PostgREST issue, however it appears everyone expects updated 3.1 version of OpenAPI spec, which postgrest doesn't support. Is this use case expected to be covered by PostREST feature, https://postgrest.org/en/stable/releases/v10.0.0.html#openapi ?
