### DISCUSSION TITLE
InDB config is not working

### DISCUSSION THREAD

**Discussion by mfatihercik** [PostgREST/postgrest#2944] [Q&A] [answered]
Hi, I want to use dynamic schema feature, and I followed the documentation but couldn't make it work.
I am getting following error:

 **(PGRST106) The schema must be one of the following: public**

docker-compose file

```

version: "3.9"

services:
  postgres:
    image: "postgres:13-alpine"
    command: "postgres -c listen_addresses='*'"
    ports:
      - "5432:5432" # expose the port for local dev
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "authenticator"
      POSTGRES_PASSWORD: "password"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U authenticator -d app" ]
      interval: 10s
      timeout: 10s
      retries: 3

  postgrest:
    image: "postgrest/postgrest:latest"
    expose:
      - "8888"
    ports:
      - "8888:8888"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGRST_DB_URI: "postgresql://authenticator:password@postgres:5432/app?sslmode=disable"
      #      PGRST_DB_SCHEMAS: "api"
      PGRST_DB_CONFIG: true
      PGRST_JWT_SECRET_IS_BASE64: "false"
      PGRST_SERVER_PORT: "8888"
      PGRST_LOG_LEVEL: "info"
      PGRST_DB_PRE_CONFIG: postgrest.pre_config
      PGRST_JWT_SECRET: "reallyreallyreallyreallyverysafe"
  #      PGRST_OPENAPI_MODE: "follow-privileges"

  
```

created  api schema:

```
create schema IF NOT EXISTS api;

-- create a role to api schema
create role api_role nologin;
--grant usage on schema api to api_role;
GRANT USAGE ON SCHEMA api TO api_role;

-- grant privileges to the user for future view and table creation
ALTER DEFAULT PRIVILEGES IN SCHEMA api GRANT SELECT,UPDATE,INSERT,DELETE ON TABLES TO api_role;

CREATE OR REPLACE VIEW api.location AS
SELECT * FROM public.location;

```

dynamic schema:

```
create schema postgrest;

grant usage on schema postgrest to authenticator;


create or replace function postgrest.pre_config()
    returns void as $$
select
    set_config('pgrst.db_schemas', 'api', true)
$$ language sql;
```

I copied the sql query that fetches DB config, and it is showing the schemas.

```
WITH
    role_setting AS (
        SELECT setdatabase as database,
               unnest(setconfig) as setting
        FROM pg_catalog.pg_db_role_setting
        WHERE setrole = CURRENT_USER::regrole::oid
          AND setdatabase IN (0, (SELECT oid FROM pg_catalog.pg_database WHERE datname = CURRENT_CATALOG))
    ),
    kv_settings AS (
        SELECT database,
               substr(setting, 1, strpos(setting, '=') - 1) as k,
               substr(setting, strpos(setting, '=') + 1) as v
        FROM role_setting
        union
            SELECT
    null as database,
    x as k,
    current_setting(x, true) as v
        FROM pg_catalog.unnest(string_to_array('pgrst.db_schemas','db_schemas2')) x
            join postgrest.pre_config() on true
    )
SELECT DISTINCT ON (key)
    replace(k, '{prefix}', '') AS key,
    v AS value
FROM kv_settings
WHERE k = ANY(string_to_array('pgrst.db_schemas','db_schemas2')) AND v IS NOT NULL
ORDER BY key, database DESC NULLS LAST
```
Result of the Above Query:
| key | value |
| pgrst.db_schemas | api |

When I run the following queries, it is working but in the documentation, it is mentioned that this is not the recommended way to do it.

`ALTER ROLE authenticator SET pgrst.db_schemas = 'public,api';`

Can someone help on how to make and in-db configuration work
