### DISCUSSION TITLE
PostgREST Only Exposing First Schema in PGRST_DB_SCHEMAS List

### DISCUSSION THREAD

**Discussion by gabrielstellini** [PostgREST/postgrest#3109] [Q&A] [answered]
### Environment

* PostgreSQL version: postgres:15
* PostgREST version: [v12.0.1](https://hub.docker.com/layers/postgrest/postgrest/v12.0.1/images/sha256-d3d040b53ed98cf4281266589523943cf727cc30b43cdcec346f073842042122?context=explore)
* Operating system: Linux, Debian

### Description of issue

The following is a sample from my docker-compose file:

```
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest:latest
    ports:
      - 8082:3000
    environment:
      - PGRST_DB_URI=postgres://${APP_DB_USER}:${APP_DB_PASSWORD}@postgres:5432/${APP_DB}
      - PGRST_DB_ANON_ROLE=pg_custom_anon
      - PGRST_DB_SCHEMAS=schema1,schema2,schema3
      - PGRST_JWT_ROLE_CLAIM_KEY=[CENSORED]
      - PGRST_JWT_SECRET=${PGRST_JWT_SECRET}
      - PGRST_JWT_SECRET_IS_BASE64=false
```

Expected Behavior:
When I specify multiple schemas in the PGRST_DB_SCHEMAS environment variable, I expect all listed schemas to be loaded and exposed via the API. The [docs](https://postgrest.org/en/stable/references/configuration.html?highlight=PGRST_DB_SCHEMAS#db-schemas) specify that this parameter should accept a list

Actual Behavior:
Only the first schema listed in PGRST_DB_SCHEMAS is being exposed by the API. Reordering the schemas results in only the first schema being exposed. The exposed tables are reflected in swagger, and reordering effects the swagger definition to reflect this
