### DISCUSSION TITLE
Cloud Run Sidecar - Admin Server not returning on the ready endpoint to Cloud Run

### DISCUSSION THREAD

**Discussion by john-ramsey** [PostgREST/postgrest#3665] [Q&A]
### Environment

* PostgreSQL version: 14.12
* PostgREST version: 12.2.2
* Operating system: x86_64-pc-linux-gnu, official Docker image

### Description of issue

The admin server does not appear to report back to GCP cloud run that the service is ready upon 

Expected Behavior:
- Admin server returns `200 OK`

Actual Behavior:
- *It looks like PostgREST is starting up fine* but fails to report to cloud run. Has anyone else had this issue?

<img width="1166" alt="Screenshot 2024-07-15 at 10 28 14 PM" src="https://github.com/user-attachments/assets/94f62794-ab0a-400d-9745-e3cd4809ba34">
<img width="507" alt="Screenshot 2024-07-15 at 10 28 58 PM" src="https://github.com/user-attachments/assets/bdbcb7d1-697f-41d7-b3c9-2064a431db94">

Reproduction
1. Start a cloud run service with PostgREST as a sidecar container
2. Have the main container startup dependant on PostgREST
3. Ensure that PostgREST has a startup probe (GCP will require this)
4. PostgREST will fail to report back to Cloud Run

**Comment by steve-chavez** [comment]
Can you try with https://github.com/PostgREST/postgrest/releases/tag/v12.2.0 or https://github.com/PostgREST/postgrest/releases/tag/v12.2.1?

Just to check if it's a problem with the latest version.

**Comment by john-ramsey** [comment]
I tried both tags and neither worked for me. Were you able to recreate?

**Reply by steve-chavez** [reply]
No, I cannot reproduce. Is it possible to isolate this from cloud run?

**Reply by john-ramsey** [reply]
Just to clarify you were not able to reproduce in Cloud Run or locally? I locally I am unable to reproduce outside of cloud run which has me thinking it is a result of how Cloud Run is routing sidecar health checks.

**Comment by wolfgangwalther** [comment]
What do you have `server-host` set to? Maybe you need to change that somehow?

**Reply by wolfgangwalther** [reply]
Were you able to get this to run / figure out what the problem was?

**Reply by john-ramsey** [reply]
Unfortunately this isn't something that we have prioritized. No answer as of yet as we are operating without the probe.

**Comment by thomasjungblut** [comment]
also running this into now, any hints?

**Reply by wolfgangwalther** [reply]
Same question as above, what did you set `server-host` to?

**Comment by thomasjungblut** [comment]
in the health probe request? why would you need to set that?

**Reply by wolfgangwalther** [reply]
Both regular server and admin server listen on the same host, configured via `server-host` (as of right now). You might need to set this to ` 0.0.0.0` to have the health check work.

**Reply by thomasjungblut** [reply]
Sorry for the new discussion thread, e-mails don't seem to respond to the right place... 

I've left it to the default, setting it to 0.0.0.0 directly does not make the readiness probe return anything.

```
        env:
        - name: PGRST_SERVER_HOST
          value: 0.0.0.0
        - name: PGRST_ADMIN_SERVER_PORT
          value: '3001'
...
        startupProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          httpGet:
            path: ready
            port: 3001
```

Is a special host header required on the health probe request?
What would I also set there, I have no idea about what IP it will run on. The DNS name will only return once the probe is reporting ready.

The logs are also not insanely helpful to debug this either:

```
2024-08-25 17:29:52.895 CEST
25/Aug/2024:15:29:52 +0000: Schema cache loaded 328 Relations, 216 Relationships, 0 Functions, 0 Domain Representations, 4 Media Type Handlers, 596 Timezones
2024-08-25 17:30:17.142 CEST
STARTUP HTTP probe failed 5 times consecutively for container "postgrest-1" on path "ready". The instance was not started.
```

Is there any admin request logging I could turn on?

**Reply by wolfgangwalther** [reply]
I have this and it's working for me on my self-managed k8s cluster:

```yaml
        livenessProbe:
          httpGet:
            path: /live
            port: 3001
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
        env:
        - name: PGRST_ADMIN_SERVER_PORT
          value: "3001"
```

I didn't need to set server-host either.

**Reply by wolfgangwalther** [reply]
Just noticed again that this issue is about running PostgREST in a side-car container. It might be that server-host actually needs to be set to 127.0.0.1 for the startup probe?

Maybe you can try that. Of course, this will only work for the probe, but then serving the actual api might be broken. But if that works, then the solution will be to use the new (still unreleased) admin-server-host option.

**Reply by thomasjungblut** [reply]
It's not a sidecar btw, it's the sole running container on cloud run. 

It might be a limitation of cloudrun, which requires the exact same port (?): https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start

You can also not configure more than one container port either:
> ports should contain 0 or 1 port. (field: service.spec.template.spec.containers[0].ports)

It's a bit odd, because as you mentioned this works in k8s/knative pretty well.

**Reply by thomasjungblut** [reply]
Just for completeness sake, here's the full cloud run yaml:

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: postgrest
  generation: 24
  labels:
    cloud.googleapis.com/location: europe-west4
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Custom
      annotations:
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: 'XXX:europe-west4:XXX-master'
        autoscaling.knative.dev/maxScale: '5'
        run.googleapis.com/startup-cpu-boost: 'false'
    spec:
      containerConcurrency: 100
      timeoutSeconds: 30
      serviceAccountName: postgrest@XXX.iam.gserviceaccount.com
      containers:
      - name: postgrest-1
        image: 'gcr.io/XXX/postgrest:v12.2.3'
        ports:
        - name: http1
          containerPort: 3000
        env:
        - name: PGRST_SERVER_HOST
          value: 0.0.0.0
        - name: PGRST_ADMIN_SERVER_PORT
          value: '3001'
        - name: PGRST_DB_PRE_CONFIG
          value: postgrest.pre_config
        - name: PGRST_JWT_SECRET_IS_BASE64
          value: 'true'
        - name: PGRST_DB_URI
          valueFrom:
            secretKeyRef:
              key: latest
              name: XXX-master-postgrest-url
        - name: PGRST_JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: '1'
              name: XXX-master-postgrest-hmac
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
        startupProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          httpGet:
            path: ready
            port: 3001
  traffic:
  - percent: 100
    latestRevision: true
```
