### DISCUSSION TITLE
How can i change the logs timestamp and date format when using docker?

### DISCUSSION THREAD

**Discussion by sti-p-sdsingh** [PostgREST/postgrest#3809] [Q&A] [answered]
Hey, i am little confused regarding the timestamp and date format displayed in PostgREST's logs. I have understood that they depend on the server's timezone, but can i know, how i can change them if i am using the official docker image? I have tried changing the database's timezone but that didnt change anything.

**Comment by wolfgangwalther** [comment, marked as answer]
The "server" is not the "database" in this case, but the PostgREST server. You'll need to run PostgREST itself with that different timezone.

That means you need to set the environment variable `TZ` accordingly when running PostgREST, for example via docker.

**Reply by sti-p-sdsingh** [reply]
Thank you so much for your prompt response, @wolfgangwalther!
I tried running the container with env variable tz set to the following, but it didnt work. 
Am i doing something wrong?

```
postgrest:
    image: postgrest/postgrest
    restart: always
    ports:
      - 3002:3000
    environment:
      PGRST_DB_URI: ****
      PGRST_DB_SCHEMA: ****
      PGRST_DB_ANON_ROLE: ****
      PGRST_JWT_SECRET: ****
      PGRST_CORS_DOMAIN: "*"  
      TZ: America/New_York
    networks:
      - backend
```
