### ISSUE TITLE
Array wrapper on rpc JSONB return type

### ISSUE THREAD

**Issue by pauldzy** [PostgREST/postgrest#1376]
### Environment

* PostgreSQL version: 11.2
* PostgREST version: 6.0.1
* Operating system: Ubuntu 18.04.3

### Description of issue

Under version 5.2, RPC functions returning JSONB were rendered "as-is" on output.  This allowed, for example, to return a GeoJSON collection object ready for ingestion by Leaflet.

Version 6.0.0 and 6.0.1 now return results from the same function encased in an array wrapper.

Is this a bug or a change in behavior?

Thanks!

example function whereby return JSONB should just render as specified
```
CREATE OR REPLACE FUNCTION myschema.geojc()
RETURNS JSONB
STABLE
AS
$BODY$ 
DECLARE   
BEGIN   
   RETURN jsonb_build_object(
       'type','FeatureCollection'
      ,'features',NULL
   );
END;
$BODY$
LANGUAGE plpgsql;
```

**Comment by steve-chavez** [comment]
@pauldzy What's the wrong output you see and the desired output?

I don't see an array wrapper when testing that function myself:

```json
{"type": "FeatureCollection", "features": null}
```

**Comment by steve-chavez** [comment]
Probably a stale schema cache case http://postgrest.org/en/v5.2/admin.html#schema-reloading, make sure you restart or SIGUSR1 postgrest when adding a new function.

**Comment by pauldzy** [comment]
Thanks for the speedy review, Steve.  However, I get this result consistently with the 6.0.x version starting from scratch with no previously existing code.

Here is my bare-bones docker-compose file

```
version: "3.7" 
services:
    pg:
        image: postgres:11
        hostname: pg
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - target: 5432
              published: 5432
        networks:
            - dz
    pr:
        image: postgrest/postgrest
        hostname: pr
        environment:
            PGRST_DB_URI: postgres://postgres:password@pg:5432/postgres
            PGRST_DB_SCHEMA: public
            PGRST_DB_ANON_ROLE: postgres
        ports:
            - target: 3000
              published: 3000
        networks:
            - dz
networks:
    dz:
        driver: bridge
```

when I toss my sample routine into the fresh public schema and call it via
http://localhost:3000/rpc/geojc

my response is 
**[**{"geojc":{"type": "FeatureCollection", "features": null}}**]**
with the unwanted array brackets.

Is there some other way I could troubleshoot this?

Cheers,
Paul

![image](https://user-images.githubusercontent.com/4131067/62966837-dcb45400-bdd5-11e9-9ab8-d040d0c805d2.png)
