### ISSUE TITLE
Error: JWSError (JSONDecodeError "Not valid base64url")"

### ISSUE THREAD

**Issue by samkhawase** [PostgREST/postgrest#1434]
### Environment

* PostgreSQL version: postgresql:alpine
* PostgREST version: postgrest:latest
* Operating system: Linux

### Description of issue

I'm creating a demo application for an internal demo. I create a new setup using docker compose, which bootstraps the postgresql server as well. I'm using Auth0 to get the JWT. However the requests fail with the following error:
```

{
    "message": "JWSError (JSONDecodeError \"Not valid base64url\")"
}
```

Steps to reproduce: 
1. Start the server using docker-compose:

```
version: '3'
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
      - "./scripts:/docker-entrypoint-initdb.d"
  server:    
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: api_anon
      PGRST_ROLE_CLAIM_KEY: ".\"https://postgrest-demo/role\""
      PGRST_JWT_SECRET: "{\"alg\":\"RS256\",\"kty\":\"RSA\",\"use\":\"sig\",\"n\":\"x2zhxS_3PLPrIhiDWyB1Q-hRzUBsIU5To07Pw1ktlOFCid7qYwQB6_-RmDu9SITorkAXQtH2kZTJg1Pp987UivAYjgFlpvUrUYIp-FWlPiNVfey0FQzYP11Db4zRhRXSt4LPJM_QDX9GRJ_-6cxiz1_m0LWmDXnQzloaWHP0yJHzz04d_wTYsTFnwjujIx735mvuHXSrfWAYgooGGW0OZKUWjYq1gojj7z3wtw6_iv7inOiUPI63Gvkx5bmieSLRz3cCzzvvCQXMMy8OGc9wT-Svai94YVHCGdCxdjEgMnkWFr3oxmRWBK8DGmfonj5amv3EfSh35AkaDJm2SSCq_w\",\"kid\":\"RUZBQUE2Rjg4NzNCMkIzQTAxNTlGQjIyNTA2QzAyQTAxNjEwOTZBOA\",\"e\":\"AQAB\"}"
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
```

The mounted **./scripts/init-db.sql** file has the following contents:
```
CREATE SCHEMA api;

SET search_path TO api;

drop table if exists api.amenity;
drop table if exists api.review;

-- Ratings enum instead of asking user to type in
create type rating as enum ('positive', 'neutral', 'negative');

create table api.amenity (
    amenity_id serial primary key,
    amenity_name text not null,
    amenity_address text not null,
    created_on timestamptz not null default now()
);

create table api.review (
    review_id serial primary key,
    review_rating rating,
    review_text text,
    created_on timestamptz not null default now(),
    amenity_id integer not null references api.amenity(amenity_id)
);

-- Create users

CREATE ROLE api_user nologin;
CREATE ROLE api_anon nologin;

GRANT USAGE on SCHEMA api to api_anon;
GRANT SELECT on api.amenity to api_anon;
GRANT SELECT on api.review to api_anon;

grant usage on schema api to api_user;
grant all on api.amenity to api_user;
grant all on api.review to api_user;

```

2. Issue a curl request to localhost:3000/
```
curl --location --request GET 'http://localhost:3000/review' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJVWkJRVUUyUmpnNE56TkNNa0l6UVRBeE5UbEdRakl5TlRBMlF6QXlRVEF4TmpFd09UWkJPQSJ9.eyJodHRwczovL3Bvc3RncmVzdC1kZW1vL3JvbGUiOiJhcGlfdXNlciIsIm5pY2tuYW1lIjoiY2hhbXBha2xhbCIsIm5hbWUiOiJjaGFtcGFrbGFsQG1haWxpbmF0b3IuY29tIiwicGljdHVyZSI6Imh0dHBzOi8vcy5ncmF2YXRhci5jb20vYXZhdGFyLzFiZDhkZGYxYzhkMGQ2NmQ2YjAxNTI5ZDE0ZjMwOTlhP3M9NDgwJnI9cGcmZD1odHRwcyUzQSUyRiUyRmNkbi5hdXRoMC5jb20lMkZhdmF0YXJzJTJGY2gucG5nIiwidXBkYXRlZF9hdCI6IjIwMjAtMDEtMDhUMjA6NDI6NDYuNjY5WiIsImlzcyI6Imh0dHBzOi8vcG9zdGdyZXN0LWRlbW8uZXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDVlMTVkNDFmNDdlOWY2MGVhN2YyMGViZSIsImF1ZCI6IlNCWFFTZ3k3b0NtM0dMSzlLZlEwVk9Ecm1ycnNDaEl3IiwiaWF0IjoxNTc4NTE2MzAwLCJleHAiOjE1Nzg1NTIzMDB9.NSXSYCoHi0_Hi6fiA_YUT7zJCkNB0sh9428EjjBcJT15h5GvrVYX6FqU5F0jeo--D4oZWtAv3mP4uwbYrU5ZYN9iZ64f0Japm2V1DKzO4TsJsPrejWGfa9LHmAE8gDZB3lQOrdA5c7EenS4CnWlqZCr8Vjh6Uz_fym23x9fMg_SPdaQe2XccQdmDkWOxCQ9puH_hVfK2ho6DR0UfJuZ8Sw7G6NArnkuv9smjOlgFJA0VpSfO15I3VF-0dteuDbxXNJiVVcmSd7ddiPA9KojaGcr5tt56agJ-0ruRVLlxLBZrCp15WoYj5wcCSpUSqp6X0'
```

**Result**: The request fails with the following error:

```
{
    "message": "JWSError (JSONDecodeError \"Not valid base64url\")"
}
```

I searched in existing issues, but couldn't find anything that could help me resolve the issue. Any help is highly appreciated.

**Comment by steve-chavez** [comment]
You could try using a file for the secret, see https://github.com/PostgREST/postgrest/issues/1192#issuecomment-446632584 for an example.

**Comment by samkhawase** [comment]
I tried that as well, but still got the same error:
`Bearer error="invalid_token", error_description="JWSError (JSONDecodeError \"Not valid base64url\")"`

Here's the modified part of the `docker-compose.yml`
```
server:    
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: api_anon
      PGRST_ROLE_CLAIM_KEY: ".\"https://postgrest-demo.de/role\""
      PGRST_JWT_SECRET: "@/opt/config/rsa.jwk.pub"
    volumes:
      - "./certs/rsa.jwk.pub:/opt/config/rsa.jwk.pub"
    depends_on:
      - db
```

Here's the content of my `rsa.jwk.pub` from `https://postgrest-demo.eu.auth0.com/.well-known/jwks.json`. Is there anything wrong here?

```
{
  "alg": "RS256",
  "kty": "RSA",
  "use": "sig",
  "n": "x2zhxS_3PLPrIhiDWyB1Q-hRzUBsIU5To07Pw1ktlOFCid7qYwQB6_-RmDu9SITorkAXQtH2kZTJg1Pp987UivAYjgFlpvUrUYIp-FWlPiNVfey0FQzYP11Db4zRhRXSt4LPJM_QDX9GRJ_-6cxiz1_m0LWmDXnQzloaWHP0yJHzz04d_wTYsTFnwjujIx735mvuHXSrfWAYgooGGW0OZKUWjYq1gojj7z3wtw6_iv7inOiUPI63Gvkx5bmieSLRz3cCzzvvCQXMMy8OGc9wT-Svai94YVHCGdCxdjEgMnkWFr3oxmRWBK8DGmfonj5amv3EfSh35AkaDJm2SSCq_w",
  "kid": "RUZBQUE2Rjg4NzNCMkIzQTAxNTlGQjIyNTA2QzAyQTAxNjEwOTZBOA",
  "e": "AQAB"
}
```
