### ISSUE TITLE
Add authentication to swagger

### ISSUE THREAD

**Issue by Hedgehogues** [PostgREST/postgrest#1514]
### Environment

* PostgreSQL version: latest
* PostgREST version: latest
* Operating system: Ubuntu 18.04

### Description of issue

Hello. I start postgrest with next docker-compose:

```
version: "3"
services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
  db:
    restart: always
    image: "postgres:11"
    container_name: "atm_postgres"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
    ports:
      - '5432:5432'
    volumes:
      - ./data/my_dbdata:/var/lib/postgresql/data
```

and next postgrest config:

```
db-uri = "postgresql://test:test@0.0.0.0:5432/test_db"
db-schema = "api"
db-anon-role = "web_anon"
jwt-secret = "ZaYmgVILsN1fOonIZdrNHm3ZChg0VrWP"
```

I go to the swagger and I cannot post new item therefore swagger has not header with authentication:

![image](https://user-images.githubusercontent.com/4973667/80963263-41598800-8e17-11ea-98c2-26d27fb5010f.png)

How I fix it?
