### ISSUE TITLE
Failed to Fetch error on Swagger UI

### ISSUE THREAD

**Issue by jmaldon1** [PostgREST/postgrest#1580]
### Environment

* PostgreSQL version: AWS RDS PostgreSQL version 11.5
* PostgREST version: docker latest image ID befe6cd943da
* Swagger UI version: docker latest image ID 2bf56948221e
* Operating system: Windows 10 WSL2 (Ubuntu 20.04.1 LTS)

### Description of issue

docker-compose.yaml

```yaml
version: '3'
services:
  server:
    env_file:
      - .env
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://${PGUSER}:${PGPASS}@${HOSTNAME}:5432/postgres?sslmode=require
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: app_user
      # PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3000/"
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/

```

I am getting various failed to fetch errors when trying to use the swagger UI.

When running on `Chrome` browser:
I am getting a `TypeError: Failed to fetch` error when using the swagger UI. When looking at the browser dev console i get `net::ERR_ADDRESS_INVALID`.

When running on `Firefox` browser:
I am getting a `TypeError: NetworkError when attempting to fetch resource.` error when using the swagger UI. When looking at the browser dev console I get `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://0.0.0.0:3000/outfits. (Reason: CORS request did not succeed).`.

Everything works fine when hitting the postgrest server from any other means besides browser such as Postman or Curl.

The strange part is that I have a macbook that I ran this same `docker-compose up` on and the swagger UI works over there (same versions of everything).
