### ISSUE TITLE
Field names are lost in distributed table

### ISSUE THREAD

**Issue by haohanyang** [PostgREST/postgrest#1784]
### Environment

* PostgreSQL version: (if using docker, specify the image)
docker citusdata/citus:10.0.3
postgrest/postgrest:latest
* PostgREST version: (if using docker, specify the image)
docker postgrest/postgrest:latest
* Operating system:
macOS Big Sur

### Description of issue
(Expected behavior vs actual behavior)

I am using [Citus](https://www.citusdata.com/)(distributed postgres) along with postgrest so I can get JSON from `HTTP /<table_name>`. It goes well for undistributed tables but for distributed tables the field names are missing and I get `f1, f2, f3, ...` instead. 

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)

Download the [docker-compose.yml](https://raw.githubusercontent.com/citusdata/docker/master/docker-compose.yml) and [data](https://examples.citusdata.com/tutorial/companies.csv). Also add the following in the `services:` of `docker-compose.yml`

``` yaml
  restful:
    container_name: 'postgrest'
    image: 'postgrest/postgrest'
    environment:
      PGRST_DB_URI: "postgres://postgres@master:5432/postgres"
      PGRST_DB_SCHEMA: ""
      PGRST_DB_ANON_ROLE: "postgres"
    ports:
      - "3000:3000"
```
Setup the cluster
``` bash
docker-compose -p citus up
```
Add data into the container
```
docker cp companies.csv citus_master:.
```
Go into the master and create table
```
docker exec -it citus_master psql -U postgres

CREATE TABLE companies (
    id bigint NOT NULL,
    name text NOT NULL,
    image_url text,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

\copy companies from 'companies.csv' with csv

```
Then `http://localhost:3000/companies` get normal table rows. 

But if I do the following in the master container after that 
```
SELECT create_distributed_table('companies', 'id');

```
Then `http://localhost:3000/companies` get normal table rows without field names but `f1, f2, f3 ...`
