### ISSUE TITLE
no api response

### ISSUE THREAD

**Issue by npltr62** [PostgREST/postgrest#1889]
### Environment

* PostgreSQL version: kartoza/postgis:13
* PostgREST version: postgrest:v7.0.1
* Operating system:
NAs synology
### Description of issue
here is docker-compose
```   
    image: postgrest/postgrest
    ports:
      - "49321:3000" #local port: contener port
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user
      PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3000
```
then in the journal 
```
listening on port 3000
connection successful
```
server address = 10.8.2.1
but when i try to connect  like in [documentation](https://postgrest.org/en/stable/how-tos/casting-type-to-custom-json.html) http://10.8.2.1:8751/reservations
I have no response from api :/
![err](https://user-images.githubusercontent.com/40625762/124629277-9365c580-de81-11eb-944b-fb1def2887c5.png)
