### ISSUE TITLE
[Question] Postgrest overhead w.r.t direct DB query

### ISSUE THREAD

**Issue by unarmedcivilian** [PostgREST/postgrest#2005]
### Environment

* PostgreSQL version: AWS RDS 13.3 (2 vCPU, 8GB Mem)
* PostgREST version: Docker (postgrest/postgrest:v8.0.0)
```
# 4 Pods
resources:
    limits:
        cpu: 1500m
        ephemeral-storage: 1Gi
        memory: 256Mi
    requests:
        cpu: 750m
        ephemeral-storage: 250Mi
        memory: 256Mi
```
* Operating system: AWS EKS (1.15)

### Description of issue
We ran some load tests comparing Postgrest against direct DB queries, and saw that the overhead is significant. The setup is described below.

```
create table if not exists perf_test (
    id         bigserial,
    name       text,
    value      jsonb,
    created_at timestamp with time zone default now() not null
);

create index if not exists idx_id
    on perf_test (id);
```
Table has ~ 2M rows. 

Tests were executed from K8s using [Locust](https://docs.locust.io/en/stable/quickstart.html).

Benchmark DB query
```
def execute_query(self):
    id =  random.randint(1, 2000000)
    id2 = id + 20
    self.client.execute_query("select * from perf_test where id between {0} and {1}".format(id, id2))
```

Benchmark Postgrest request
```
def get_perf_test(self):
    id = random.randint(1, 2000000)
    id2 = id + 20
    headers = {'Accept-Encoding': 'gzip', 'Connection': 'Keep-Alive', 'Keep-Alive': 'timeout=5, max=2000'}
    self.client.get(f"/perf_test?id=geq.{id}&id=le.{id2}", name="/perf_test", headers=headers)
```
 The DB queries are able to scale up to 2K TPS with a latency (P95) of ~ 2ms.  The corresponding Postgrest requests are topping off at ~ 10ms (P95) with a TPS of ~50. 

Is this amount of overhead expected? 
Are there any recommended configurations / best practices to optimize throughput and latency of Postgrest?
Are there any benchmarks that you have done with this kind of comparison?
