### ISSUE TITLE
Bug: custom jwt claims not recognised in Postgres 14

### ISSUE THREAD

**Issue by ewan-escience** [PostgREST/postgrest#2100]
### Environment

* PostgreSQL version: postgres:13.4 and postgres:14.1 (Docker)
* PostgREST version: postgrest/postgrest:v9.0.0.20211220 (Docker)
* Operating system: Linux Mint 20.2

### Description of issue
Create a file called `init.sql` with the following content: 
```
CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD 'simplepassword';

CREATE ROLE web_anon NOLOGIN;

GRANT USAGE ON SCHEMA public TO web_anon;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO web_anon;

GRANT web_anon TO authenticator;

CREATE ROLE my_role NOLOGIN;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO my_role;

GRANT my_role TO authenticator;

CREATE TABLE mytable (
	mycolumn VARCHAR PRIMARY KEY
);

INSERT INTO mytable VALUES ('abc');

ALTER TABLE mytable ENABLE ROW LEVEL SECURITY;

CREATE POLICY only_users_with_email_can_read ON mytable FOR SELECT TO my_role
	USING (current_setting('request.jwt.claim.email', FALSE) IS NOT NULL);

```

Create a file called `docker-compose.yml` with the following content: 
```
version: '3'
services:
  server:
    image: postgrest/postgrest:v9.0.0.20211220
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:simplepassword@db:5432/app_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_JWT_SECRET: reallyreallyreallyreallyverysafe
    depends_on:
      - db
  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

```

Now run `docker-compose up` and visit http://localhost:3000/mytable with header`Authorization` with value `Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoibXlfcm9sZSIsImVtYWlsIjoiam9obkBkb2UuY29tIn0.pkhcV33ydVYmdD2YPFDZqkPmS6L54HAKDxaGzOuZlOM`.

You should get status code `200` and body:
```
[
	{
		"mycolumn": "abc"
	}
]
```

Now change the postgres version to `14.1`. Run `docker-compose down` and `docker-compose up`. Make the same request as above. Now you won't get the expected result. The status code will be `400` and the response body will be
```
{
	"hint": null,
	"details": null,
	"code": "42704",
	"message": "unrecognized configuration parameter \"request.jwt.claim.email\""
}
```

So custom claims don't work with Postgres 14.
