### ISSUE TITLE
Schema cache not updating after Notify

### ISSUE THREAD

**Issue by yacine-learning** [PostgREST/postgrest#2319]
### Environment

* PostgreSQL version: 12.11
* PostgREST version: postgrest/postgrest:v9.0.0
* Operating system: Ubuntu

### Description of issue

Notify seems to correctly update the db-schemas parameter on the postgrest container but the API does not seem to see this change unless I restart the container.

Steps to reproduce:

- On the db: `ALTER ROLE authenticator SET pgrst.db_schemas = 'nyc, tokyo, london';`
- Start postgREST container and check the config with: `docker exec -it 8e6b3842eed postgrest --dump-config`
- I can see that `db-schemas` is correctly set: `db-schemas = "nyc,tokyo,london"`
- Now I modify the pgrst.db_schemas and do a notify:
`ALTER ROLE authenticator SET pgrst.db_schemas = 'nyc,tokyo,london,amsterdam';`
`NOTIFY pgrst, 'reload schema';`
- Check the postgREST config again, and I can see that db-schemas has been updated with the new value:
 `db-schemas = "nyc,tokyo,london,amsterdam"`
- However the following call: 
` curl "http://localhost:3000/message" -H "Authorization: Bearer $TOKEN" -H "Accept-Profile: amsterdam"` will give the following error:
`{"message":"The schema must be one of the following: nyc, tokyo, london"}`

But ` curl "http://localhost:3000/message" -H "Authorization: Bearer $TOKEN" -H "Accept-Profile: tokyo"`  is still working fine.
The only way to fix this is by restarting the container, which I wanted to avoid by using Notify. 
Am I doing something wrong?

Here is my postgrest config, right after the container starts:
```
db-anon-role = "anonymous"
db-channel = "pgrst"
db-channel-enabled = true
db-extra-search-path = "public"
db-max-rows = ""
db-pool = 10
db-pool-timeout = 10
db-pre-request = ""
db-prepared-statements = true
db-root-spec = ""
db-schemas = "nyc,tokyo,london"
db-config = "true"
db-tx-end = "commit"
db-uri = "postgresql://XXXX@XXXX:5432/testing?sslmode=require"
db-use-legacy-gucs = true
jwt-aud = ""
jwt-role-claim-key = ".\"role\""
jwt-secret = "XXXXXXXXX"
jwt-secret-is-base64 = false
log-level = "error"
openapi-mode = "follow-privileges"
openapi-server-proxy-uri = ""
raw-media-types = ""
server-host = "!4"
server-port = 3000
server-unix-socket = ""
server-unix-socket-mode = "660"
```

And here's the docker-compose:
```
version: '3'
services:
  server:
    image: postgrest/postgrest:v9.0.0
    domainname: "postgrest001"
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgresql://XXXX:XXXX@XXXXX:5432/testing?sslmode=require
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anonymous
      PGRST_JWT_SECRET: "XXXXXX"
```
