### ISSUE TITLE
Should Request Headers be Displayed When a Request is Made to a Stored Procedure? 

### ISSUE THREAD

**Issue by eceppda** [PostgREST/postgrest#2434]
### Environment

* PostgreSQL version: postgres:12.12 (docker container)
* PostgREST version: postgrest/postgrest:v9.0.1.20220802 (docker container)
* Operating system: macos

### Description of issue

I've written a function to retrieve request headers.

I have added the following stored procedure in postgres:

```
CREATE FUNCTION schema.get_headers()
RETURNS json AS $$
 SELECT current_setting('request.headers', true)::json;
$$ LANGUAGE SQL IMMUTABLE;
```

And I'm testing it using curl and postgrest:
```
curl http://localhost:3000/schema/rpc/get_headers -H "User-Agent: Mozilla"
```

The response is:

`{}`

### (Expected behavior vs actual behavior)

My expectation is that all request headers will be returned in json format. In particular, since I've specified a request header (`User-Agent`) in my curl request, I expected to see it when I made a request to the rpc url.

Instead, I receive an empty json response.

### (Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)

The question should be reproducible using the above function and curl command. I'm using a compose file similar to this:
```
  db:
    image: postgres:12.12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: schema
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
  
  server:
    image: postgrest/postgrest:v9.0.1.20220802
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://dbuser:password@db:5432/schema
      PGRST_DB_SCHEMA: schema
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_USE_LEGACY_GUCS: "False"
    depends_on:
      - db
```
