### ISSUE TITLE
Unexpectedly High CPU Usage during Load test

### ISSUE THREAD

**Issue by bhupixb** [PostgREST/postgrest#2490]
### Environment

* PostgreSQL version: 13.7
* PostgREST version: v9.0.0
* Operating system: AWS EKS Linux(5.10.x+ kernel version)

### Description of issue

We are doing some load tests on PostgREST. Postgrest is running on Kubernetes pods with 2 replicas. It connects to AWS-managed PostgreSQL RDS.
During the load testing, we are seeing out of the 2 pods running, 1 of the pod CPU spikes very high. In the below pic, we can see that CPU usage of 1 of the pod went to almost 6 cores. 
![image](https://user-images.githubusercontent.com/30554307/192525822-f1438d62-2dd4-41bc-9ea1-b8cf23fb5d33.png)

Initially, we suspected that one pod might be serving more requests than the other, but from the metrics, we saw both pods are serving almost the same no. of requests per second(QPS):
![image](https://user-images.githubusercontent.com/30554307/192526001-bbcd0d54-70ec-44f1-97f9-04247694a193.png)

This is **happening every time we do the load test**, even if we scale pods to more than 2, to say 5 pods. Then we see similar behaviour with 1/2 pods and the rest of the pods keep using normal CPU.

### Expected Behaviour
Since both pods are serving the same no. of requests per second, the CPU usage difference should not be this huge.

### Actual Behaviour
CPU usage for a few pods is quite high as compared to others despite serving almost same amount of traffic.

### Pod config for postgrest
```yaml
requests:
  cpu: 1.5
  mem: 1Gi
limits:
  cpu: 3
  mem: 2Gi
replicas: 2
```
Postgrest Configuration:
```yaml
  PGRST_DB_POOL: "10"
  GHCRTS: "-qg -I0"
```

(Steps to reproduce: Include a minimal SQL definition plus how you make the request to PostgREST and the response body)
Sample Deployment file:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
spec:
  replicas: 2
  selector:
    matchLabels:
      test: test
  template:
    metadata:
      labels:
        test: test
    spec:
      containers:
        - env:
            - name: PGRST_DB_URI
              value: "<REDACETED>"
            - name: PGRST_DB_SCHEMA
              value: public
            - name: PGRST_JWT_SECRET
              value: <REDACETED>
            - name: GHCRTS
              value: '-qg -I0'
            - name: PGRST_DB_ANON_ROLE
              value: <REDACETED>
            - name: PGRST_DB_POOL
              value: '10'
            - name: PGRST_DB_POOL_TIMEOUT
              value: '300'
          image: postgrest/postgrest:v9.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /postgrest_health
              port: http-postgrest
          name: postgrest
          ports:
            - containerPort: 3000
              name: http-postgrest
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /postgrest_health
              port: http-postgrest
          resources:
            limits:
              cpu: 3
              memory: 2Gi
            requests:
              cpu: 1.5
              memory: 1Gi
```
Any suggestion from the community on what things can be checked to find the root cause will be appreciated. Please let me know if I need to share any other info.
