### ISSUE TITLE
Unable to authenticate using third-party OAuth without role claim

### ISSUE THREAD

**Issue by Javiervva** [PostgREST/postgrest#3002]
### Environment

* PostgreSQL version: Docker bitnami/postgresql:13.8.0
* PostgREST version: Docker postgrest/postgrest:latest (v11.2.1)
* Operating system: Windows 10 Enterprise with Docker Desktop 4.17.1 (using Docker's WSL 2 based engine, not a traditional Linux distribution like Ubuntu) without Kubernetes.

### Description of issue
Hello,

I'm currently attempting to integrate PostgREST into a system that employs its own OAuth2 for securing the service. The challenge I'm facing is that the JWT payload we send to PostgREST doesn't contain the user's role. Due to security constraints, we are provided with an access_token in the OIDC when logging in via the SSO in the application. This token is what we must use for subsequent calls to retrieve roles. This creates an issue for us. From my understanding (please correct me if I'm mistaken), this role claim seems to be mandatory when using a third-party OAuth to identify the role that should be assigned in the database. However, in our scenario, there shouldn't be any role or permission distinctions. Only authorized users can log into our application, and being logged in implies they have full access. For this reason, we also don't see a need for an anonymous user, as we don't want anyone accessing without authentication. Our application is straightforward with limited functionalities, which is why we initially opted for PostgREST instead of setting up microservices.

I conducted several tests using the .sub (username) and added a role with my username, granting it the necessary permissions. This approach worked. However, assigning a role for each individual user, department, floor, or any other basic token information is unfeasible for us to maintain. This leads me to the core of my inquiry: Is there a way that if the PGRST_JWT_ROLE_CLAIM_KEY environment variable isn't specified, PostgREST would simply verify the JWT's signature against the JWKS specified in the PGRST_JWT_SECRET environment variable?

Lastly, we would prefer to achieve this without the need to implement a custom PostgreSQL function in our database, if possible.

Docker-compose setup
```
version: '3'

services:
  postgrest:
    image: postgrest/postgrest:latest
    environment:
      PGRST_DB_URI: postgres://authenticator:password@psql/db
      # PGRST_SERVER_HOST: 0.0.0.0
      # PGRST_SERVER_PORT: 3000
      PGRST_DB_SCHEMA: <schema>
      PGRST_JWT_SECRET: "@/etc/postgrest/public_key.rsa.jwk.pub"
      PGRST_JWT_SECRET_IS_BASE64: false
      PGRST_JWT_AUD: <aud>
      PGRST_ROLE_CLAIM_KEY: .sub
      # PGRST_JWT_CACHE_MAX_LIFETIME: 86400
      PGRST_DB_CONFIG: false
      PGRST_LOG_LEVEL: info
      # PGRST_SERVER_TRACE_HEADER: X-Request-Id
      # PGRST_DB_ANON_ROLE: anon
      PGRST_OPENAPI_MODE: 'ignore-privileges'
      PGRST_OPENAPI_SECURITY_ACTIVE: true
      # PGRST_OPENAPI_SERVER_PROXY_URI: http://nginx:80
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - psql
    volumes:
      - ./public_key.rsa.jwk.pub:/etc/postgrest/public_key.rsa.jwk.pub
    ports:
      # - "127.0.0.1:3000:3000"
      - "3000:3000"
    networks:
      - localnet

  psql:
    image: bitnami/postgresql:13.8.0
    restart: always
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
      # to load init tables
      - './init_db:/docker-entrypoint-initdb.d'
    environment:
      - POSTGRESQL_USERNAME=username
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
      - POSTGRESQL_POSTGRES_PASSWORD=mysecretpostgrespass
    ports:
      - "8081:5432"
    networks:
      - localnet

  swagger:
    image: swaggerapi/swagger-ui:latest
    depends_on:
    - postgrest
    ports:
    - "8080:8080"
    environment:
      API_URL: http://localhost:3000/
    networks:
      - localnet

networks:
  localnet:

volumes:
  postgresql_master_data:
```

Setup database:
```
-- Create the 'authenticator' role with limited permissions. This role will be used by PostgREST 
-- to first connect to the database and then switch to the appropriate user role.
CREATE ROLE authenticator LOGIN NOINHERIT NOCREATEDB NOCREATEROLE NOSUPERUSER PASSWORD '<password>';

-- Create a user role named '<my_usercode>'. This represents the user code obtained from the JWT's '.sub' claim.
-- It's an example of how you might set up roles for individual users based on their JWT.
CREATE ROLE "<my_usercode>" LOGIN NOINHERIT NOCREATEDB NOCREATEROLE NOSUPERUSER PASSWORD '<password>';

-- Allow the 'authenticator' role to switch to the '<my_usercode>' role.
GRANT "<my_usercode>" TO authenticator;

-- Grant the schema usage permission to '<my_usercode>'.
GRANT USAGE ON SCHEMA <schema> TO "<my_usercode>";

-- Grant '<my_usercode>' the SELECT permission on the table in the specified schema.
GRANT SELECT ON TABLE <schema>.<table> TO "<my_usercode>";
```

With this setup, when I am the logged-in user and we send that JWT, PostgREST verifies the role against the database, assigns it, and with the necessary permissions set on it, the generated endpoints work correctly. However, when we disable the PGRST_JWT_ROLE_CLAIM_KEY environment variable, we receive a 401 Unauthorized response with the following body:
```
{
    "code": "PGRST301",
    "details": null,
    "hint": null,
    "message": "JWSError JWSInvalidSignature"
}
```

And the header reads:
```
WWW-Authenticate: Bearer error="invalid_token", error_description="JWSError JWSInvalidSignature"
```

For us, it would be ideal to know if there's a possibility for PostgREST to simply validate the JWT token against the JWKS for signature verification. If that's successful, and in the absence of a role claim and no anonymous role, we'd like to use the primary user for all operations. This would allow us to bypass the chameleon functionality, as it wouldn't be necessary in our case.
### (Expected behavior vs actual behavior)

| Aspect              | Current Behavior                                                                                          | Expected Behavior                                                                                                       |
|---------------------|----------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------|
| JWT Role Validation | Requires a role claim. Returns 401 Unauthorized with "JWSError JWSInvalidSignature" when not provided. | Validate the JWT token against the JWKS. If successful, use the primary user for all operations, bypassing chameleon. |

##### Define the following environment variables:
```
PGRST_JWT_SECRET: "@/etc/postgrest/public_key.rsa.jwk.pub"
PGRST_JWT_SECRET_IS_BASE64: false
PGRST_JWT_AUD: <aud>
```
##### Omit Role Claim Key:
Ensure that the PGRST_JWT_ROLE_CLAIM_KEY environment variable is not set.

##### Disable Anonymous Role:
Comment out or omit the following line to deactivate the anonymous role:
```
# PGRST_DB_ANON_ROLE: anon
```
#### 2. Database configuration
Execute the following SQL command to set up the required role in your database:
```
CREATE ROLE authenticator LOGIN NOINHERIT NOCREATEDB NOCREATEROLE NOSUPERUSER PASSWORD '<password>';
```
Note: Also add permissions to schemas/tables where necessary.
#### 3. Make a Request:
Send a request to an exposed PostgREST endpoint, passing the JWT token in the 'Authorization' header.

#### 4. Observe the Error:
The response body should be:
```
{
    "code": "PGRST301",
    "details": null,
     "hint": null,
     "message": "JWSError JWSInvalidSignature"
}
```
