### ISSUE TITLE
docs: catch invalid target references

### ISSUE THREAD

**Issue by steve-chavez** [PostgREST/postgrest#4106]
## Problem

On https://github.com/PostgREST/postgrest/pull/4099#discussion_r2111130776, an invalid reference was not caught by `linkcheck`.

```
With `RPC <functions>`_, the preference is honored completely on the basis of the number of rows returned in the result set of the function. This can be useful for complex mutation queries using `data-modifying statements <https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-MODIFYING>`_.
```

Tthe "functions" reference is invalid here and when clicked on rendered docs it redirected to a "404 not found".

## Solution

Looks like we can use `nitpicky` for this:

> In nitpicky mode, Sphinx will warn about all references where the target cannot be found.
> https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-nitpicky-mode

## Notes

If the above doesn't work maybe https://github.com/rstcheck/rstcheck can help?

**Comment by steve-chavez** [comment]
>  It was caught by linkcheck! But we only run linkcheck once a week, not on every PR. I fixed it after receiving the error notification.

Got it, cool. How did you get the error notification? I didn't get any 😿

**Comment by steve-chavez** [comment]
> Maybe we could make the linkcheck post a comment to a designated issue. This way all of us could get the notifications.

That would be great 🚀

**Comment by taimoorzaeem** [comment]
This could work? Maybe we can use this issue for "reporting" the link check failure.

```yaml
jobs:
  linkcheck:
     ...

 on-linkcheck-fail:
    runs-on: ubuntu-latest
    needs: linkcheck
    if: needs.linkcheck.result == 'failure'
    steps:
      - name: Notify on linkcheck failure by commenting
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: 4106
          body: |
            ❌ **Linkcheck Job Failed!**
            
            other details...        
```
